title: Rural Tech
description: Rural Tech's software page
repository: rural-tech/rural-tech.github.io
theme: just-the-docs

url: https://rural-tech.github.io

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

favicon_ico: "/assets/images/favicon.ico"

search_enabled: false
nav_enabled: true

back_to_top: true
back_to_top_text: "Back to top"

mathjax: true
latex: mathjax

sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ["import"] # https://github.com/just-the-docs/just-the-docs/issues/1607
